#!/bin/bash

echo "Getting hostname" >> /dev/kmsg
host="$(grep '^hostname:' /boot/device-init.yaml | sed 's/hostname: \(.*\)/\1/g')"

echo "Renaming hostname to ${host}" >> /dev/kmsg
echo "${host}" > /etc/hostname
cat << EOF > /etc/hosts
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       ${host}
EOF

echo "Changing password" >> /dev/kmsg
password="$(grep '^password:' /boot/device-init.yaml | sed 's/password: \(.*\)/\1/g')"
echo "pi:${password}" | chpasswd

echo "Updating Home Assistant configuration" >> /dev/kmsg
python /usr/local/bin/setup_homeassistant.py

echo "Setting up ngrok" >> /dev/kmsg
python /usr/local/bin/setup_ngrok.py

echo "Enabling ngrok" >> /dev/kmsg
/usr/local/bin/ngrok service install -config /home/pi/.ngrok2/ngrok.yaml
/usr/local/bin/ngrok service start
