#!/bin/bash

echo "Getting hostname" >> /dev/kmsg
host="$(grep '^hostname:' /boot/device-init.yaml | sed 's/hostname: \(.*\)/\1/g')"

echo "Renaming hostname to ${host}" >> /dev/kmsg
echo "${host}" > /etc/hostname
cat << EOF > /etc/hosts
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       ${host}
EOF

echo "Changing password" >> /dev/kmsg
password="$(grep '^password:' /boot/device-init.yaml | sed 's/password: \(.*\)/\1/g')"
echo "pi:${password}" | chpasswd
